export const siteConfig = {
  brandName: 'Mokshya Foods',
  tagline: 'Naturally dried fruits and food powders from Nepal',
  description: 'Mokshya Foods offers naturally dried food products and food powders from Nepal for everyday use, gifting, and household routines.',
  email: 'mokshyafoods@gmail.com',
  phone: '+9779761583987',
  phoneDisplay: '+977 9761583987',
  location: 'Tilottama-01, Rupandehi, Banbitika, Butwal, Nepal',
  hours: 'Mon - Fri: 9:00 AM - 6:00 PM',
  whatsapp: 'https://wa.me/9761583987',
  instagram: 'https://www.instagram.com/mokshyafoods',
  facebook: 'https://www.facebook.com/mokshyafoods',
  tiktok: 'https://www.tiktok.com/@mokshya66',
  shippingNote: 'We deliver across Nepal. Free delivery is available within town; outside-town delivery is based on distance and may be charged up to Rs 150.',
  refundNote: 'Please contact us promptly for order concerns, returns, or product issues.',
};
